sudo: required

language: generic

services:
        - docker

before_install:
        - docker build -t pk219/test_client -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true pk219/test_client npm test

after_success:
        - docker build -t pk219/multi-client ./client
        - docker build -t pk219/multi-nginx ./nginx
        - docker build -t pk219/multi-server ./server
        - docker build -t pk219/multi-worker ./worker
        - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
        - docker push pk219/multi-client
        - docker push pk219/multi-nginx
        - docker push pk219/multi-server
        - docker push pk219/multi-worker
