sudo: required

language: generic

services:
        - docker

before_install:
        - docker build -t test_client -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true test_client npm test

after_success:
        - docker build -t multi-client ./client
        - docker build -t multi-nginx ./nginx
        - docker build -t multi-server ./server
        - docker build -t multi-worker ./worker
        - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
        - docker push multi-client
        - docker push multi-nginx
        - docker push multi-server
        - docker push multi-worker
